### ISSUE TITLE
Unexpected Identifier

### ISSUE THREAD

**Issue by nmbarker** [terkelg/prompts#32]
I don't know what I did wrong I'll provide whatever files to help with debugging.
const response = await prompts ({
------------------------                                        ^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3

EDIT:
I've also run into the issue with the error: "SyntaxError: await is only valid in async function"

**Comment by rainrivas** [comment]
I have the same problem with trying to run the sample code block.
```javascript
// index.js
const prompts = require('prompts');

const response = await prompts({
    type: 'number',
    name: 'value',
    message: 'How old are you?'
});

console.log(response); // => { value: 23 }
```
then I try calling `node index.js` and see the following error
```
const response = await prompts({
                       ^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Node and NPM version:
```
$ node -v;npm -v
v8.9.4
5.6.0
```

**Comment by lukeed** [comment]
Hey guys,

Prompts requires that you be in Node 7.6 or later. Although, since 7.6 isn't an LTS release, you should be on 8.x or later.

Version 7.6 was when native `AsyncFunction` was introduced. 

Also, if you're trying to run the examples as is, they're meant to be illustrative. They need to be run within an `async` function, which is standard/required usage for the two.

You can see #18 for a little more follow up~!

**Comment by nmbarker** [comment]
@lukeed  I fixed my issue thank you for your help. I just needed to incase it in a async function and change a few things.
