### ISSUE TITLE
TypeError: Cannot set property 'selected' of undefined

### ISSUE THREAD

**Issue by xvishaldongre** [terkelg/prompts#320]
### Describe the bug
I am just playing with prompts and wanted to use the `autocompleteMultiselect` type of prompt. And this is where i found the bug.

### To Reproduce

1. make simple `autocompleteMultiselect` type of prompt.
2. give it choices.
3. now run the file.
4. and search anything 
5. than choices until `No matches for this query.` appear
5. and press `left` or `right` key and you will get an error.

### Expected behavior
Nothing will happen.

### Happend behavior
You will get an error like this: 
```
TypeError: Cannot set property 'selected' of undefined
    at AutocompleteMultiselectPrompt.right (/home/user/test/node_modules/prompts/lib/elements/autocompleteMultiselect.js:63:48)
    at ReadStream.keypress (/home/user/test/node_modules/prompts/lib/elements/prompt.js:32:16)
    at ReadStream.emit (node:events:365:28)
    at emitKeys (node:internal/readline/utils:358:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (node:readline:1281:36)
    at ReadStream.emit (node:events:377:35)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at ReadStream.Readable.push (node:internal/streams/readable:228:10)
```
### System

- OS: Linux Mint 20.1 x86_64
- Terminal: gnome-terminal, zsh 5.8
- Node version: v16.0.0

### Additional
Image Before error:
![image](https://user-images.githubusercontent.com/32993907/125115891-9377f680-e109-11eb-9f68-7d37a9c019f9.png)

Image After error:
![image](https://user-images.githubusercontent.com/32993907/125116007-b30f1f00-e109-11eb-9e25-571b4f6fcc34.png)

**Comment by nvuillam** [comment]
@xvishaldongre i have the same issue... did you find a workaround?
